# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outil',
            name='isBuy',
        ),
        migrations.AlterField(
            model_name='outil',
            name='isDispo',
            field=models.BooleanField(default=True),
        ),
    ]
