# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170810_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autre',
            name='text',
            field=models.CharField(default='-------------------------', max_length=25),
        ),
        migrations.AlterField(
            model_name='famille',
            name='nom',
            field=models.CharField(default='Famille', max_length=75),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(default='Fournisseur', max_length=50),
        ),
        migrations.AlterField(
            model_name='histoligne',
            name='stockChange',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nom',
            field=models.CharField(default='Outil', max_length=75),
        ),
        migrations.AlterField(
            model_name='outil',
            name='numSerie',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='pignouf',
            name='nom',
            field=models.CharField(default='Nom', max_length=50),
        ),
        migrations.AlterField(
            model_name='pignouf',
            name='prenom',
            field=models.CharField(default='Prenom', max_length=50),
        ),
        migrations.AlterField(
            model_name='sousfamille',
            name='nom',
            field=models.CharField(default='Sous-Famille', max_length=75),
        ),
    ]
